project2/urls.py
from django.conf import settings
from django.conf.urls.static import static
"""project2 URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('sports.urls')),

]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

sports/urls.py
from django.urls import path
from . import views
app_name = 'sports'
urlpatterns = [path('', views.sportss, name='home'),
               # path('loop/', views.loop, name='house'),
               path('login/', views.jaya, name='login-page'),
               path('logout/', views.out, name='logout-page'),
               path('register/', views.reg, name='register-page'),
               path('about/', views.about, name='about-page'),
               path('blog/', views.blog, name='blog-page'),
               path('team/', views.team, name='team-page'),
               path('contact/', views.contact, name='contact-page'),
               path('news/', views.news, name='news-page'),
               path('search/', views.search, name='searchresult-page'),
               path('singleblog/<int:id>', views.singleblog, name='singleblog-page'),
               path('botton/', views.botton, name='botton-page'),
               path('contactbox/', views.contactbox, name='contact-box')

               ]

sports/models.py
from django.db import models


class sports(models.Model):
    date = models.DateField(auto_now_add=True)
    head = models.CharField(max_length=500)
    sub = models.CharField(max_length=10000)
    img = models.ImageField(upload_to='pics')


class match(models.Model):
    date = models.DateTimeField(auto_now_add=False)
    team1 = models.CharField(max_length=100)
    team2 = models.CharField(max_length=100)
    logo1 = models.ImageField(upload_to='isl')
    logo2 = models.ImageField(upload_to='isl')


class cricket(models.Model):
    date = models.DateTimeField(auto_now_add=False)
    team1 = models.CharField(max_length=100)
    team2 = models.CharField(max_length=100)
    logo1 = models.ImageField(upload_to='ipl')
    logo2 = models.ImageField(upload_to='ipl')


class comment(models.Model):
    class Meta:
        app_label = 'sports'

    name = models.CharField(max_length=300)
    email = models.EmailField(max_length=300)
    address = models.CharField(max_length=300)
    message = models.CharField(max_length=300)

class readmore(models.Model):
    image = models.ImageField(upload_to='blog_pics')
    heading = models.CharField(max_length=400)
    discription = models.CharField(max_length=500)
    date = models.DateField(auto_now_add=True, blank=True, null=True)

sports/views.py
from django.shortcuts import render, redirect
from .models import sports
from .models import match, readmore
from .models import cricket, comment
from django.contrib.auth.models import auth, User
from django.contrib import messages
from django.db.models import Q
from project2.settings import EMAIL_HOST_USER
from django.core.mail import send_mail


# firstmatch = sports()
# firstmatch.date = '1/12/1997'
# firstmatch.head = 'it was a good match'
# firstmatch.sub = 'fgfhagsa gfjhadvafgjshdfvns hhsgdfjbsvdcnggs sggdfnbdfsd nsgdf usgf hgfjfhsvjff'
#
# secondmatch = sports()
# secondmatch.date = '12 12 12'
# secondmatch.head = 'amazing match'
# secondmatch.sub = 'super kaliyaan mwone'
# secondmatch.img = 'peace.jpg'
#
# thirdmatch = sports()
# thirdmatch.date = '10 10 10'
# thirdmatch.head = 'shimmi hero aada hero'
# thirdmatch.sub = 'mwone ath lockaa ing por'
# thirdmatch.img = 'psyco.jpeg'
#
# fourmatch = sports()
# fourmatch.date = '12 12 1998'
# fourmatch.head = 'vamban game'
# fourmatch.sub = 'walare migacha onn'
# fourmatch.img = 'messi.jpg'
# fourmatch.img = 'ronu.jpg'
# fourmatch.img = 'vijay.jpg'

# lis = [firstmatch, secondmatch, thirdmatch, fourmatch]


def sportss(request):
    ob = sports.objects.all()
    mt = match.objects.all()
    ab = cricket.objects.all()

    return render(request, 'index.html', {'objects': ob,
                                          'mt': mt, 'ab': ab})


# def sport(request):
#   mt = match.objects.all()


# return render(request, 'index.html', {'matches': mt})


# def loop(request):
#     return render(request, 'forloop.html', {'f': lis})


def jaya(request):
    if request.method == 'POST':
        a = request.POST['name']
        b = request.POST['password']
        user = auth.authenticate(username=a, password=b)
        if user is not None:
            auth.login(request, user)
            return redirect('sports:home')
        else:
            messages.error(request, "invalid username/password")

    return render(request, 'login.html')


def out(request):
    auth.logout(request)
    return redirect('sports:home')


def reg(request):
    if request.method == 'POST':
        c = request.POST['fullname']
        d = request.POST['youremail']
        e = request.POST['password']
        f = request.POST['confirm-password']
        g = request.POST['firstname']
        h = request.POST['lastname']
        print(c, d, g, h)
        if (e == f):

            if (User.objects.filter(username=c).exists()):
                messages.error(request, "username already exist")
                return redirect('sports:register-page')
            elif (User.objects.filter(email=d).exists()):
                messages.error(request, "email already exist")
                return redirect('sports:register-page')
            else:
                z = User.objects.create_user(username=c, email=d, password=e, first_name=g, last_name=h)
                z.save()
                auth.login(request, z)
                return redirect('sports:home')
        else:
            messages.error(request, "password doesn't match")
            return redirect('sports:register-page')
    return render(request, 'register.html')


def about(request):
    subject = 'Welcome to Noc Tech solutions'
    message = 'Hope you are enjoying your Django Tutorials'
    recepient = request.GET.get('comment')
    send_mail(subject,
              message, EMAIL_HOST_USER, [recepient], fail_silently=False)
    return render(request, 'about.html', {'b': recepient})


def blog(request):
    ad = readmore.objects.order_by('-date')[0:1]
    bd = readmore.objects.order_by('date')[1:]

    return render(request, 'Blog.html', {'ad': ad, 'bd': bd})


def team(request):
    return render(request, 'team.html')


def contact(request):
    return render(request, 'contact.html')


def news(request):
    return render(request, 'news.html')


def search(request):
    a = request.GET.get('f', None)
    results = sports.objects.filter(Q(head__icontains=a) | Q(sub__icontains=a))
    result = match.objects.filter(Q(team1__icontains=a) | Q(team2__icontains=a))
    return render(request, 'searchresult.html', {'search': results, 'search': result})


def singleblog(request, id):
    cd = readmore.objects.get(id=id)
    return render(request, 'single-blog.html', {'cd': cd})


def botton(request):
    return render(request, 'botton.html')


def contactbox(request):
    name = request.POST.get('name', None)
    email = request.POST.get('email', None)
    address = request.POST.get('address', None)
    message = request.POST.get('message', None)
    print(name, email, address, message)
    comment.objects.create(name=name, email=email, address=address, message=message)
    return render(request, 'contactbox.html')

templates/Blog.html
{% extends 'base.html' %}
{%load static%}
{% block content %}

<body class="game_info" data-spy="scroll" data-target=".header">
<!-- LOADER -->
<div id="preloader">
    <img class="preloader" src="{%static 'images/loading-img.gif'%}" alt="">
</div>
<!-- END LOADER -->
<section id="top">

    <div class="inner-page-banner">
        <div class="container">
        </div>
    </div>
    <div class="inner-information-text">
        <div class="container">
            <h3>Blog</h3>
            <ul class="breadcrumb">
                <li><a href="{% url 'sports:home' %}">Home</a></li>
                <li class="{%url 'sports:blog-page'%}">Blog</li>
            </ul>
        </div>
    </div>
</section>

<section id="contant" class="contant main-heading team">
    <div class="row">
        <div class="container">
            <div class="col-md-9">
                {% for ad in ad %}
                <div class="feature-post">
                    <div class="feature-img">
                        <img src="{{ad.image.url}}" class="img-responsive" alt="#"/>
                    </div>
                    <div class="feature-cont">
                        <div class="post-people">
                            <div class="left-profile">
                                <div class="post-info">
                                    <img src="{% static 'images/profile-img.png'%}" alt="#"/>
                                    <span>

                                    <h4>by George Kvasnikov</h4>
                                    <h5>{{ad.date}}</h5>
                                 </span>
                                </div>
                                <span class="share"></span>
                            </div>
                        </div>
                        <div class="post-heading">
                            <h3>{{ad.heading}}</h3>
                            <p>{{ad.discription}}
                            </p>
                            <div class="full">
                                <a class="btn" href="{% url 'sports:singleblog-page' ad.id %}">Read More</a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}


                {% for ad in bd %}
                <div class="feature-post small-blog">
                    <div class="col-md-5">
                        <div class="feature-img">
                            <img src="{{ad.image.url}}" class="img-responsive" alt="#"/>
                        </div>
                    </div>
                    <div class="col-md-7">
                        <div class="feature-cont">
                            <div class="post-info">
                                <img src="{% static 'images/profile-img.png'%}" alt="#"/>
                                <span>
                                 <h4>by George Kvasnikov</h4>
                                 <h5>{{ad.date}}</h5>
                              </span>
                            </div>
                            <div class="post-heading">
                                <h3>{{ad.heading}}</h3>
                                <p>{{ad.discription}}</p>
                                <div class="full">
                                    <a class="btn" href="{% url 'sports:singleblog-page' ad.id %}">Read More</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                {% endfor %}
            </div>
            <div class="col-md-3">
                <div class="blog-sidebar">
                    <div class="search-bar-blog">

                        <form>
                            <input type="text" placeholder="search"/>
                            <button><i class="fa fa-search" aria-hidden="true"></i></button>
                        </form>
                    </div>
                </div>
                <div class="blog-sidebar">
                    <h4 class="heading">Top Categories</h4>
                    <div class="category-menu">
                        <ul>
                            <li><a href="#">Cricket</a></li>
                            <li><a href="#">Football</a></li>
                            <li><a href="#">Hockey</a></li>
                            <li><a href="#">Tennis</a></li>
                            <li><a href="#">Basketball</a></li>
                            <li><a href="#">Golf</a></li>
                            <li><a href="#">Cycling</a></li>
                            <li><a href="#">Motorsports</a></li>
                        </ul>
                    </div>
                </div>
                <div class="blog-sidebar">
                    <h4 class="heading">Popular News</h4>
                    <div class="category-menu">
                        <ul>
                            <li>
                                <span><img src="{% static 'images/profile-img2.png'%}" alt="#"></span>
                                <span>
                                 <p>Two touch penalties, imaginary cards</p>
                                 <p class="date">22 Feb, 2016</p>
                              </span>
                            </li>
                        </ul>
                    </div>
                </div>
                <aside id="sidebar" class="left-bar">
                    <div class="feature-matchs">
                        <div class="team-btw-match">
                            <ul>
                                <li>
                                    <img src="{% static 'images/img-01_002.png'%}" alt="">
                                    <span>Portugal</span>
                                </li>
                                <li class="vs"><span>vs</span></li>
                                <li>
                                    <img src="{% static 'images/img-02.png'%}" alt="">
                                    <span>Germany</span>
                                </li>
                            </ul>
                            <ul>
                                <li>
                                    <img src="{% static 'images/img-03_002.png'%}" alt="">
                                    <span>Portugal</span>
                                </li>
                                <li class="vs"><span>vs</span></li>
                                <li>
                                    <img src="{% static 'images/img-04_003.png'%}" alt="">
                                    <span>Germany</span>
                                </li>
                            </ul>
                            <ul>
                                <li>
                                    <img src="{% static 'images/img-05_002.png'%}" alt="">
                                    <span>Portugal</span>
                                </li>
                                <li class="vs"><span>vs</span></li>
                                <li>
                                    <img src="{% static 'images/img-06.png'%}" alt="">
                                    <span>Germany</span>
                                </li>
                            </ul>
                            <ul>
                                <li>
                                    <img src="{% static 'images/img-07_002.png'%}" alt="">
                                    <span>Portugal</span>
                                </li>
                                <li class="vs"><span>vs</span></li>
                                <li>
                                    <img src="{% static 'images/img-08.png'%}" alt="">
                                    <span>Germany</span>
                                </li>
                            </ul>
                        </div>
                    </div>
                </aside>
                <aside id="sidebar" class="left-bar">
                    <div class="banner-sidebar">
                        <img class="img-responsive" src="{% static 'images/match-banner1.jpg'%}" alt="#">
                        <h3>Argentina vs Chile|Goals of the match | COPA </h3>
                    </div>
                </aside>
                <aside id="sidebar" class="right-bar">
                    <div class="banner">
                        <img class="img-responsive" src="{% static 'images/adds-3.jpg' %}" alt="#">
                    </div>
                </aside>
                <aside id="sidebar" class="left-bar">
                    <div class="feature-matchs">
                        <table class="table table-bordered table-hover">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Team</th>
                                <th>P</th>
                                <th>W</th>
                                <th>L</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td>1</td>
                                <td><img src="{% static 'images/img-01_004.png'%}" alt="">Liverpool</td>
                                <td>10</td>
                                <td>12</td>
                                <td>20</td>
                            </tr>
                            <tr>
                                <td>2</td>
                                <td><img src="{% static 'images/img-02_002.png'%}" alt="">Chelsea</td>
                                <td>10</td>
                                <td>12</td>
                                <td>20</td>
                            </tr>
                            <tr>
                                <td>3</td>
                                <td><img src="{% static 'images/img-03_003.png'%}" alt="">Norwich City</td>
                                <td>20</td>
                                <td>15</td>
                                <td>20</td>
                            </tr>
                            <tr>
                                <td>4</td>
                                <td><img src="{% static 'images/img-04_002.png'%}" alt="">West Brom</td>
                                <td>60</td>
                                <td>10</td>
                                <td>60</td>
                            </tr>
                            <tr>
                                <td>5</td>
                                <td><img src="{% static 'images/img-05.png'%}" alt="">sunderland</td>
                                <td>30</td>
                                <td>06</td>
                                <td>30</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </aside>
            </div>
        </div>
    </div>
</section>

<a href="#home" data-scroll class="dmtop global-radius"><i class="fa fa-angle-up"></i></a>
<!-- ALL JS FILES -->

</body>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% include 'head.html' %}
</head>
<body>
    {% include 'header.html' %}
    {% block content %}
    {% endblock content %}
    {% include 'footer.html' %}
    {% include 'script.html' %}
</body>
</html>

templates/botton.html
<body>
<h> asthala vistha baybay </h>

</body>

templates/contactbox.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h>AND HERE WE GO </h>

</body>
</html>

templates/header.html
{%load static%}
{%static 'images' as baseUrl%}
<header>
    <div class="container">
        <div class="header-top">
            <div class="row">
                <div class="col-md-6">
                    <div class="full">
                        <div class="logo">
                            <a href="index.html"><img src="{%static 'images/logo.png'%}" alt="#"/></a>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="right_top_section">
                        <!-- social icon -->
                        <ul class="social-icons pull-left">
                            <li><a class="facebook" href="https://www.facebook.com"><i class="fa fa-facebook"></i></a>
                            </li>
                            <li><a class="twitter" href="https://www.twitter.com"><i class="fa fa-twitter"></i></a></li>
                            <li><a class="youtube" href="https://www.youtube.com"><i class="fa fa-youtube-play"></i></a>
                            </li>
                            <li><a class="pinterest" href="https://www.pinterest.com/"><i class="fa fa-pinterest-p"></i></a>
                            </li>
                        </ul>
                        <!-- end social icon -->
                        <!-- button section -->
                        <ul class="login">
                            {% if user.is_authenticated %}
                            <li class="logout-modal">
                                <a href="{% url 'sports:logout-page'%}" class="logout"><i class="fa fa-user"></i>Logout</a>
                            </li>
                            {% else %}
                            <li class="login-modal">
                                <a href="{% url 'sports:login-page'%}" class="login"><i class="fa fa-user"></i>Login</a>
                            </li>
                            <li>
                                <div class="cart-option">
                                    <a href="{% url 'sports:register-page' %}"><i class="fa fa-shopping-cart"></i>Register</a>
                                </div>
                            </li>
                            {% endif %}
                        </ul>
                        <!-- end button section -->
                    </div>
                </div>
            </div>
        </div>
        <div class="header-bottom">
            <div class="row">
                <div class="col-md-12">
                    <div class="full">
                        <div class="main-menu-section">
                            <div class="menu">
                                <nav class="navbar navbar-inverse">
                                    <div class="navbar-header">
                                        <button class="navbar-toggle" type="button" data-toggle="collapse"
                                                data-target=".js-navbar-collapse">
                                            <span class="sr-only">Toggle navigation</span>
                                            <span class="icon-bar"></span>
                                            <span class="icon-bar"></span>
                                            <span class="icon-bar"></span>
                                        </button>
                                        <a class="navbar-brand" href="#">Menu</a>
                                    </div>
                                    <div class="collapse navbar-collapse js-navbar-collapse">
                                        <ul class="nav navbar-nav">
                                            <li class="active"><a href="{% url 'sports:home' %}">Home</a></li>
                                            <li><a href="{% url 'sports:about-page' %}">About</a></li>
                                            <li><a href="{% url 'sports:team-page' %}">Team</a></li>
                                            <li><a href="{% url 'sports:news-page' %}">News</a></li>
                                            <li class="dropdown mega-dropdown">
                                                <a href="match" class="dropdown-toggle"
                                                   data-toggle="dropdown">Match<span class="caret"></span></a>
                                                <ul class="dropdown-menu mega-dropdown-menu">
                                                    <li class="col-sm-8">
                                                        <ul>
                                                            <li class="dropdown-header">Men Collection</li>
                                                            <div id="menCollection" class="carousel slide"
                                                                 data-ride="carousel">
                                                                <div class="carousel-inner">
                                                                    <div class="item active">
                                                                        <div class="banner-for-match"><a href="#"><img
                                                                                class="img-responsive"
                                                                                src="{%static 'images/match-banner1.jpg'%}"
                                                                                alt="#"/></a></div>
                                                                    </div>
                                                                    <!-- End Item -->
                                                                    <div class="item">
                                                                        <div class="banner-for-match"><a href="#"><img
                                                                                class="img-responsive"
                                                                                src="{%static 'images/match-banner1.jpg'%}"
                                                                                alt="#"/></a></div>
                                                                    </div>
                                                                    <!-- End Item -->
                                                                    <div class="item">
                                                                        <div class="banner-for-match"><a href="#"><img
                                                                                class="img-responsive"
                                                                                src="{%static 'images/match-banner1.jpg'%}"
                                                                                alt="#"/></a></div>
                                                                    </div>
                                                                    <!-- End Item -->
                                                                </div>
                                                                <!-- End Carousel Inner -->
                                                                <!-- Controls -->
                                                                <a class="left carousel-control" href="#menCollection"
                                                                   role="button" data-slide="prev">
                                                                    <span class="glyphicon glyphicon-chevron-left"
                                                                          aria-hidden="true"></span>
                                                                    <span class="sr-only">Previous</span>
                                                                </a>
                                                                <a class="right carousel-control" href="#menCollection"
                                                                   role="button" data-slide="next">
                                                                    <span class="glyphicon glyphicon-chevron-right"
                                                                          aria-hidden="true"></span>
                                                                    <span class="sr-only">Next</span>
                                                                </a>
                                                            </div>
                                                            <!-- /.carousel -->
                                                        </ul>
                                                    </li>
                                                    <li class="col-sm-4">
                                                        <ul class="menu-inner">
                                                            <li class="dropdown-header">Next Matchs</li>
                                                            <li><a href="#">Contrary vs classical</a></li>
                                                            <li><a href="#">Discovered vs undoubtable</a></li>
                                                            <li><a href="#">Contrary vs classical</a></li>
                                                            <li><a href="#">Discovered vs undoubtable</a></li>
                                                            <li><a href="#">Contrary vs classical</a></li>
                                                            <li><a href="#">Discovered vs undoubtable</a></li>
                                                            <li><a href="#">Contrary vs classical</a></li>
                                                            <li><a href="#">Discovered vs undoubtable</a></li>
                                                        </ul>
                                                    </li>
                                                </ul>
                                            </li>
                                            <li><a href="{% url 'sports:blog-page' %}">Blog</a></li>
                                            <li><a href="{% url 'sports:contact-page' %}">contact</a></li>
                                        </ul>
                                    </div>
                                    <!-- /.nav-collapse -->
                                </nav>
                                <div class="search-bar">
                                    <form action="{% url 'sports:searchresult-page' %}">
                                        <div id="imaginary_container">
                                            <div class="input-group stylish-input-group">

                                                <input type="text" class="form-control" name="f" placeholder="Search">
                                                <span class="input-group-addon">
                                                <button type="submit"><i class="fa fa-search"
                                                                         aria-hidden="true"></i></button>
                                                </span>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

templates/searchresult.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Search result</title>
</head>
<body>
{% for i in search %}
<p>and here is {{i.head}}</p>
<p>{{i.sub}}</p>
<p>{{i.team1}}</p>
<p>{{i.team2}}</p>
{% endfor %}

</body>
</html>

templates/sports.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
hellllo...
</body>
</html>